//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.18033
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzLib.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Sql {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Sql() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AzLib.Properties.Sql", typeof(Sql).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   OUTPUT DELETED.* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DeletedOutput {
            get {
                return ResourceManager.GetString("DeletedOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DELETE
        ///FROM
        ///	{0}
        ///	{1}
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DeleteQueryFormat {
            get {
                return ResourceManager.GetString("DeleteQueryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DROP DATABASE {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DropDatabaseFormat {
            get {
                return ResourceManager.GetString("DropDatabaseFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DROP TABLE {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DropTableFormat {
            get {
                return ResourceManager.GetString("DropTableFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OUTPUT INSERTED.{0}
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InsertedOutputFormat {
            get {
                return ResourceManager.GetString("InsertedOutputFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   INSERT INTO {0}
        ///{1}
        ///VALUES({2}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InsertQueryFormat {
            get {
                return ResourceManager.GetString("InsertQueryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SELECT
        ///	{0}
        ///FROM
        ///	{1}
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SelectQueryFormat {
            get {
                return ResourceManager.GetString("SelectQueryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TRUNCATE TABLE {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TruncateFormat {
            get {
                return ResourceManager.GetString("TruncateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}
        ///OUTPUT
        ///		{1}
        ///	,	{2} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UpdatedOutputFormat {
            get {
                return ResourceManager.GetString("UpdatedOutputFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UPDATE {0} SET
        ///{1}
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UpdateQueryFormat {
            get {
                return ResourceManager.GetString("UpdateQueryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   WHERE
        ///	{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WhereQueryFormat {
            get {
                return ResourceManager.GetString("WhereQueryFormat", resourceCulture);
            }
        }
    }
}
